<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "csv2html"
 *
 * Auto generated by Extension Builder 2020-02-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'csv2html',
    'description' => 'wacon_cvs2html is a simple and easy-to-use extension that allows you to convert a cvs file into a html table(or any other html structure). After the plugin is installed on the desired page the content will be updated whenever the file is replaced or edited. No import processes or database tables needed!',
    'category' => 'plugin',
    'author' => 'Kerstin Schmitt',
    'author_email' => 'info@wacon.de',
    'author_company' => 'WACON Internet GmbH',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
